FROM maven:3-jdk-8

MAINTAINER Go About <tech@goabout.com>

ENV BRANCH=master \
    JAVA_MX=1G

RUN apt-get -yqq update && \
    apt-get install -yqq python && \
    apt-get -yqq install python-pip && \
    pip install python-dateutil && \
    git clone https://github.com/s3tools/s3cmd.git /opt/s3cmd && \
    ln -s /opt/s3cmd/s3cmd /usr/bin/s3cmd && \
    mkdir /tmp/build && \
    cd /tmp/build && \
    wget -O src.zip --progress dot:mega https://github.com/opentripplanner/OpenTripPlanner/archive/$BRANCH.zip && \
    unzip src.zip && \
    cd OpenTripPlanner-$BRANCH && \
    mvn package -DskipTests && \
    mkdir -p /usr/local/share/java && \
    mv target/otp-*shaded.jar /usr/local/share/java/otp.jar && \
    rm -r /tmp/build ~/.m2/repository
    
COPY otp /usr/local/bin/
COPY files/s3cfg /opt/.s3cfg
COPY files/main.sh /opt/main.sh

RUN chmod 755 /usr/local/bin/*
RUN chmod 755 /opt/main.sh
RUN chmod 755 /opt/.s3cfg

# Folders for s3cmd optionations
RUN mkdir /opt/src
RUN mkdir /opt/dest

EXPOSE 8080

ENTRYPOINT /opt/main.sh  &&  \
                               /usr/local/bin/otp  --graphs opt/  --router dest  --server  
